server:
  port: 8077

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    # loadbalancer的相关配置
    loadbalancer:
      nacos:
        enabled: true
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=500,expireAfterWrite=30s
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
          lower-case-service-id: true
      # 配置路由规则，lb为负载均衡
      routes:
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*),/$\{path}/v3/api-docs
#        - id: service-one
#          uri: lb://service-one
#          predicates:
#            - Path=/service-one/**
#        - id: service-two
#          uri: lb://service-two
#          predicates:
#            - Path=/service-two/**
#        - id: test-custom-route-predicate-factory
#          uri: lb://service-one
#          # 自定义路由谓词工厂
#          predicates:
#            - TimeBetween=上午9:00,下午7:00
#          # 自定义过滤器工厂(非全局过滤器)
#          filters:
#            - PreLog=a,b

springdoc:
  swagger-ui:
    path: /swagger/index.html
    urls:
      - name: service-one
        url: /service-one/v3/api-docs
      - name: service-two
        url: /service-two/v3/api-docs
