server:
  # 设置服务的端口
  port: 8078

# 配置actuator暴露的端点以及暴露的颗粒度
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    # feign日志基于debug的日志级别
    com.yunnk.springcloudproject.FeignClient: debug
    com.alibaba.nacos: error

spring:
  application:
    name: service-two
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库账号
    username: root
    #数据库密码
    password: 162-123456
    #数据库url
    url: jdbc:mysql://127.0.0.1:3306/service-two?useUnicode=true&characterEncoding=utf8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 指定sentinel控制台的地址，控制台是懒加载，有流量才会显示
        dashboard: localhost:8080
    loadbalancer:
      nacos:
        enabled: true
#      configurations:
#        com/yunnk/springcloudproject/configuration/LoadBalancerConfiguration
    # 配置参考：https://docs.spring.io/spring-cloud-stream/docs/3.1.0/reference/html/spring-cloud-stream.html#_configuration_options
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        answer-in-0:
          binder: defaultRabbit
          destination: topic-ask
        test-in-1:
          binder: defaultRabbit
          destination: topic-test

feign:
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # 配置日志级别
        # NONE 不记录任何日志
        # BASIC 记录请求方法、URL、响应状态以及执行时间
        # HEADERS 在BASIC的基础上再记录请求头
        # FULL 记录所有信息
        loggerLevel: full
        # 配置feign拦截器，用于设置token
        requestInterceptors:
          # - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestIntecepor
  httpclient:
    # 让feign使用apache httpclient做请求，而不是默认的urlconnection，提升性能
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

# 配置seata-server
seata:
  tx-service-group: seata-${spring.application.name}
  service:
    vgroup-mapping:
      seata-${spring.application.name}: default
    grouplist:
      default: 192.168.1.1:8091
